version: '3.3'
services:
  parsley:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: "mongo:27017"
    links:
      - mongo

  mongo:
    image: mongo:3.3
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
